/**
 * PB-PIPE-COMB-CORRECTION-001 / P3-A — fabrication reference corpus.
 *
 * Main acceptance case (GO Gaspar 2026-10-08 (2)): THREE pipes at 35 deg.
 * All fabrication values below are FROZEN LITERALS derived offline from an
 * independent coordinate construction (tangent-point geometry:
 * T_in=(0,0), arc centre C=(R,0), T_out=(R-R*cos t, R*sin t), axis
 * intersection at R*tan(t/2) from each face) — they are NEVER generated by
 * calling the fabrication layer or the elbow-cut engine under test.
 *
 * Case: pipeCount=3, Di=250, Df=350, theta=35 deg, NPS 6 LR
 * (OD=168.28 mm B36.10M CROSS_REFERENCE, CLR=228.6 mm B16.9 90A /
 * Weldbend p.26 CROSS_REFERENCE), Lin=1000 mm, Lout=1200 mm,
 * weld gap g=0, fitting allowance=0.
 */

export interface FabricationPupReference {
  pipeNumber: number;
  /** Axis-to-axis REF-ENT -> E_i along the initial axis. */
  axisInMm: number;
  /** Axis-to-axis E_i -> REF-SAL along the final axis. */
  axisOutMm: number;
  /** Finished inlet pup = axisIn - t - g. */
  inletFinishedMm: number;
  /** Finished outlet pup = axisOut - t - g. */
  outletFinishedMm: number;
}

export interface PipeCombFabricationReference {
  id: string;
  pipeCount: number;
  initialSpacingMm: number;
  finalSpacingMm: number;
  elbowAngleDeg: number;
  nps: string;
  radiusType: 'LR' | 'SR';
  odMm: number;
  clrMm: number;
  inletAxisToAxisMm: number;
  outletAxisToAxisMm: number;
  weldGapMm: number;
  fittingAllowanceMm: number;
  /** Full-precision independent stagger A (P1 law, frozen). */
  staggerMm: number;
  /** Full-precision take-out t = CLR*tan(theta/2). */
  takeOutMm: number;
  /** Engine value (6-decimal rounding), documented precision 5e-7. */
  takeOutEngineMm: number;
  /** Longitudinal outlet step delta = Di*sin(theta) - A*cos(theta). */
  outletStepMm: number;
  cutIntradosMm: number;
  cutExtradosMm: number;
  keptArcLengthMm: number;
  discardedArcLengthMm: number;
  initialClearanceMm: number;
  finalClearanceMm: number;
  pups: FabricationPupReference[];
}

export const PIPE_COMB_FABRICATION_MAIN_CASE: PipeCombFabricationReference = {
  id: 'FAB-3X35',
  pipeCount: 3,
  initialSpacingMm: 250,
  finalSpacingMm: 350,
  elbowAngleDeg: 35,
  nps: '6',
  radiusType: 'LR',
  odMm: 168.28,
  clrMm: 228.6,
  inletAxisToAxisMm: 1000,
  outletAxisToAxisMm: 1200,
  weldGapMm: 0,
  fittingAllowanceMm: 0,
  staggerMm: 253.16937678185570,
  takeOutMm: 72.077303137735626,
  takeOutEngineMm: 72.077303,
  outletStepMm: -63.990103454465611,
  cutIntradosMm: 45.548063041457951,
  cutExtradosMm: 98.606543234013301,
  keptArcLengthMm: 139.64379345206629,
  discardedArcLengthMm: 219.44024685324706,
  initialClearanceMm: 81.72,
  finalClearanceMm: 181.72,
  pups: [
    {
      pipeNumber: 1,
      axisInMm: 1000,
      axisOutMm: 1200,
      inletFinishedMm: 927.92269686226439,
      outletFinishedMm: 1127.9226968622643,
    },
    {
      pipeNumber: 2,
      axisInMm: 746.83062321814430,
      axisOutMm: 1263.9901034544655,
      inletFinishedMm: 674.75332008040868,
      outletFinishedMm: 1191.9128003167298,
    },
    {
      pipeNumber: 3,
      axisInMm: 493.66124643628859,
      axisOutMm: 1327.9802069089312,
      inletFinishedMm: 421.58394329855298,
      outletFinishedMm: 1255.9029037711955,
    },
  ],
};
