/**
 * Genuine Tubero "Peines de tubería" (pipe comb) source corpus.
 * Ticket: PB-PIPE-COMB-CORRECTION-001 / P1
 *
 * Five genuine source references captured from the Tubero application and
 * independently validated in preflight R2 by an explicit coordinate
 * intersection construction (initial axes y = i*Di along X; final axes
 * IP0 + i*Df*n + t*v with v = (cos t, sin t), n = (-sin t, cos t); the
 * adjacent elbow stagger follows as A = (Df - Di*cos t)/sin t).
 *
 * `sourceDisplayedStaggerMm` is the value exactly as Tubero shows it
 * (one decimal). `independentStaggerMm` is the full-precision expected value
 * derived offline from the independent construction; the digits shown are
 * sufficient to round-trip the corresponding IEEE-754 double.
 *
 * These literals are hardcoded on purpose: expected values are NEVER
 * generated by calling the kernel under test.
 */

export interface PipeCombStaggerReference {
  id: string;
  /** Initial perpendicular centre-to-centre spacing (mm). */
  initialSpacingMm: number;
  /** Final perpendicular centre-to-centre spacing (mm). */
  finalSpacingMm: number;
  /** Elbow / direction-change angle (degrees). */
  elbowAngleDeg: number;
  /** Cota A exactly as displayed by the genuine source (one decimal, signed). */
  sourceDisplayedStaggerMm: number;
  /** Full-precision independently derived signed stagger A (mm). */
  independentStaggerMm: number;
}

export const PIPE_COMB_STAGGER_REFERENCES: readonly PipeCombStaggerReference[] = [
  {
    id: 'REF-01',
    initialSpacingMm: 200,
    finalSpacingMm: 400,
    elbowAngleDeg: 45,
    sourceDisplayedStaggerMm: 365.7,
    independentStaggerMm: 365.68542494923804043,
  },
  {
    id: 'REF-02',
    initialSpacingMm: 200,
    finalSpacingMm: 200,
    elbowAngleDeg: 45,
    sourceDisplayedStaggerMm: 82.8,
    independentStaggerMm: 82.842712474619006002,
  },
  {
    id: 'REF-03',
    initialSpacingMm: 400,
    finalSpacingMm: 200,
    elbowAngleDeg: 45,
    sourceDisplayedStaggerMm: -117.2,
    independentStaggerMm: -117.15728752538102242,
  },
  {
    id: 'REF-04',
    initialSpacingMm: 200,
    finalSpacingMm: 400,
    elbowAngleDeg: 30,
    sourceDisplayedStaggerMm: 453.6,
    independentStaggerMm: 453.58983848622455071,
  },
  {
    id: 'REF-05',
    initialSpacingMm: 200,
    finalSpacingMm: 400,
    elbowAngleDeg: 90,
    sourceDisplayedStaggerMm: 400.0,
    independentStaggerMm: 400.0,
  },
] as const;

export const PIPE_COMB_STAGGER_REFERENCE_COUNT = PIPE_COMB_STAGGER_REFERENCES.length;
