import { expect, test } from '@playwright/test';

/**
 * PB-PIPE-COMB-CORRECTION-001 — P3-B
 * Fabrication UI: optional section, workshop references, cut list, elbow
 * marking.
 *
 * Expected numbers are the FROZEN 3x35° acceptance fixture from the P3-A
 * review (Brain 6a47e94, head 39c95e3) — hand-transcribed from the reviewed
 * evidence, never generated by invoking the module under test:
 *   A = 253.169377 mm, t = 72.077303 mm,
 *   P1-IN 927.922697, P1-OUT 1127.922697, P2-IN 674.753320,
 *   P2-OUT 1191.912800, P3-IN 421.583943, P3-OUT 1255.902904 (mm).
 * Presentation format: formatLengthForUnit (mm 2 dec, in 4 dec, trailing
 * zeros trimmed, small positives auto-extended).
 */

const TOOL_URL = '/tools?t=pipe-comb&lng=en';
const TOOL_URL_ES = '/tools?t=pipe-comb&lng=es';

async function openTool(page: import('@playwright/test').Page, url: string = TOOL_URL) {
  await page.goto(url);
  const betaDialog = page.locator('div[role="dialog"][data-state="open"]');
  const shown = await betaDialog.waitFor({ state: 'visible', timeout: 10_000 }).then(() => true).catch(() => false);
  if (shown) {
    await betaDialog.getByRole('button', { name: /continuar|continue/i }).click();
    await betaDialog.waitFor({ state: 'hidden' });
  }
}

function setValues(page: import('@playwright/test').Page, values: Partial<Record<'count' | 'di' | 'df' | 'angle', string>>) {
  const map = {
    count: '#pipe-comb-pipe-count',
    di: '#pipe-comb-initial-spacing',
    df: '#pipe-comb-final-spacing',
    angle: '#pipe-comb-angle',
  } as const;
  return (async () => {
    for (const [key, selector] of Object.entries(map)) {
      const v = values[key as keyof typeof values];
      if (v === undefined) continue;
      await page.locator(selector).fill(v);
    }
  })();
}

/** Configure the complete 3x35° acceptance case (en, mm unless noted). */
async function setupCase3x35(page: import('@playwright/test').Page, url: string = TOOL_URL) {
  await openTool(page, url);
  await setValues(page, { count: '3', di: '250', df: '350', angle: '35' });
  await page.locator('[data-testid="pipe-comb-fab-toggle"]').click();
  await page.locator('#pipe-comb-fab-nps').selectOption('6');
  await page.locator('#pipe-comb-fab-lin').fill('1000');
  await page.locator('#pipe-comb-fab-lout').fill('1200');
}

function fabStatus(page: import('@playwright/test').Page) {
  return page.locator('[data-testid="pipe-comb-fab-status"]');
}

function fabMetric(page: import('@playwright/test').Page, key: string) {
  return page.locator(`[data-testid="pipe-comb-fab-metric"][data-metric="${key}"]`);
}

function pieceRow(page: import('@playwright/test').Page, id: string) {
  return page.locator(`[data-testid="pipe-comb-fab-piece"][data-piece-id="${id}"]`);
}

/* ------------------------------------------------------------------ *
 * 1. Optional section: P2 untouched
 * ------------------------------------------------------------------ */

test('fab-01: section is collapsed by default; P2 basic experience intact', async ({ page }) => {
  await openTool(page);
  const section = page.locator('[data-testid="pipe-comb-fab-section"]');
  await expect(section).toBeVisible();
  await expect(section).toHaveAttribute('data-open', 'false');
  await expect(page.locator('[data-testid="pipe-comb-fab-cutlist"]')).toHaveCount(0);
  /* P2 REF-01 defaults still work. */
  await expect(page.locator('[data-testid="pipe-comb-stagger-metric"][data-metric="cotaA"]')).toHaveText('365.69 mm');
});

test('fab-02: 3x35 complete case — summary, six pups, exact cut lengths', async ({ page }) => {
  await setupCase3x35(page);
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
  await expect(fabStatus(page)).toHaveText('Calculation complete with warnings.');
  /* Summary: take-out t and stagger A stay visually distinct. */
  await expect(fabMetric(page, 'takeOut')).toHaveText('72.08 mm');
  await expect(fabMetric(page, 'stagger')).toHaveText('253.17 mm');
  /* Six straight pups correctly associated, elbows NOT in the cut list. */
  const pups = page.locator('[data-testid="pipe-comb-fab-piece"]');
  await expect(pups).toHaveCount(6);
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('927.92 mm');
  await expect(pieceRow(page, 'P1-OUT').locator('td').nth(5)).toHaveText('1127.92 mm');
  await expect(pieceRow(page, 'P2-IN').locator('td').nth(5)).toHaveText('674.75 mm');
  await expect(pieceRow(page, 'P2-OUT').locator('td').nth(5)).toHaveText('1191.91 mm');
  await expect(pieceRow(page, 'P3-IN').locator('td').nth(5)).toHaveText('421.58 mm');
  await expect(pieceRow(page, 'P3-OUT').locator('td').nth(5)).toHaveText('1255.9 mm');
  /* Elbows identified separately (3 catalog elbows cut to 35°). */
  const elbowsNote = page.locator('[data-testid="pipe-comb-fab-elbows"]');
  await expect(elbowsNote).toBeVisible();
  expect(await elbowsNote.textContent()).toContain('3');
  expect(await elbowsNote.textContent()).toContain('35');
});

test('fab-03: P2 results and SVG unchanged while the section is open', async ({ page }) => {
  await setupCase3x35(page);
  const svg = page.locator('[data-testid="pipe-comb-stagger-svg"]');
  await expect(svg).toBeVisible();
  await expect(svg).toHaveAttribute('data-pipe-count', '3');
  await expect(page.locator('[data-testid="pipe-comb-stagger-metric"][data-metric="cotaA"]')).toHaveText('253.17 mm');
  await expect(page.locator('[data-testid="pipe-comb-stagger-row"]')).toHaveCount(3);
});

test('fab-04: close and reopen preserves the fabrication entries', async ({ page }) => {
  await setupCase3x35(page);
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
  await page.locator('[data-testid="pipe-comb-fab-toggle"]').click();
  await expect(page.locator('[data-testid="pipe-comb-fab-section"]')).toHaveAttribute('data-open', 'false');
  await page.locator('[data-testid="pipe-comb-fab-toggle"]').click();
  await expect(page.locator('#pipe-comb-fab-lin')).toHaveValue('1000');
  await expect(page.locator('#pipe-comb-fab-lout')).toHaveValue('1200');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
});

/* ------------------------------------------------------------------ *
 * 2. Reference states
 * ------------------------------------------------------------------ */

test('fab-05: both references empty — pending state, no invented lengths', async ({ page }) => {
  await openTool(page);
  await setValues(page, { count: '3', di: '250', df: '350', angle: '35' });
  await page.locator('[data-testid="pipe-comb-fab-toggle"]').click();
  await page.locator('#pipe-comb-fab-nps').selectOption('6');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'pending-refs');
  await expect(fabStatus(page)).toHaveText('Complete the references.');
  /* Planned pieces keep stable ids; lengths show absence, never 0. */
  await expect(pieceRow(page, 'P1-IN')).toHaveCount(1);
  const cutCell = await pieceRow(page, 'P1-IN').locator('td').nth(5).textContent();
  expect(cutCell).not.toContain('0 mm');
  /* Both missing references listed. */
  const missing = page.locator('[data-testid="pipe-comb-fab-missing"]');
  const missingText = (await missing.textContent()) ?? '';
  expect(missingText).toContain('Lin');
  expect(missingText).toContain('Lout');
});

test('fab-06: only Lin provided — pending with exactly Lout missing; recovery', async ({ page }) => {
  await openTool(page);
  await setValues(page, { count: '3', di: '250', df: '350', angle: '35' });
  await page.locator('[data-testid="pipe-comb-fab-toggle"]').click();
  await page.locator('#pipe-comb-fab-nps').selectOption('6');
  await page.locator('#pipe-comb-fab-lin').fill('1000');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'pending-refs');
  const missingText = (await page.locator('[data-testid="pipe-comb-fab-missing"]').textContent()) ?? '';
  expect(missingText).toContain('Lout');
  expect(missingText).not.toContain('Lin (');
  /* Recovery: completing Lout yields the full plan again. */
  await page.locator('#pipe-comb-fab-lout').fill('1200');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
  await expect(pieceRow(page, 'P3-OUT').locator('td').nth(5)).toHaveText('1255.9 mm');
});

test('fab-07: invalid reference text — review state, no stale cut list', async ({ page }) => {
  await setupCase3x35(page);
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
  await page.locator('#pipe-comb-fab-lin').fill('abc');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'review');
  await expect(page.locator('[data-testid="pipe-comb-fab-review-reason"]')).toBeVisible();
  /* The previous cut list must not stay presented as current. */
  await expect(page.locator('[data-testid="pipe-comb-fab-cutlist"]')).toHaveCount(0);
  await page.locator('#pipe-comb-fab-lin').fill('1000');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
});

test('fab-08: invalid basic P2 geometry blocks the P3 plan', async ({ page }) => {
  await setupCase3x35(page);
  await setValues(page, { di: '0' });
  await expect(page.locator('[data-testid="pipe-comb-error"]')).toBeVisible();
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'p2-invalid');
  await expect(page.locator('[data-testid="pipe-comb-fab-cutlist"]')).toHaveCount(0);
});

/* ------------------------------------------------------------------ *
 * 3. Adjustments and impossible geometry
 * ------------------------------------------------------------------ */

test('fab-09: weld gap and allowance applied once, no double discount', async ({ page }) => {
  await setupCase3x35(page);
  await page.locator('#pipe-comb-fab-gap').fill('2');
  await page.locator('#pipe-comb-fab-allowance').fill('50');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
  /* P1-IN: finished = 1000 - t - g = 925.922697; cut = +50 = 975.922697. */
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(3)).toHaveText('925.92 mm');
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(4)).toHaveText('50 mm');
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('975.92 mm');
  /* P2-IN cut = (1000 - A) - t - g + 50 = 722.753320 -> A deducted once. */
  await expect(pieceRow(page, 'P2-IN').locator('td').nth(5)).toHaveText('722.75 mm');
  /* The allowance is flagged as removed at fit-up in the detail. */
  const detail = page.locator('[data-testid="pipe-comb-fab-detail"][data-piece-id="P1-IN"]');
  await detail.locator('summary').click();
  expect(await detail.textContent()).toContain('Surplus of 50 mm');
});

test('fab-10: impossible pup length — invalid plan, non-executable pieces', async ({ page }) => {
  await setupCase3x35(page);
  await page.locator('#pipe-comb-fab-lin').fill('10');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'invalid-plan');
  await expect(pieceRow(page, 'P1-IN')).toHaveAttribute('data-status', 'invalid');
  const reason = await pieceRow(page, 'P1-IN').locator('td').nth(6).textContent();
  expect(reason?.toLowerCase()).toContain('invalid');
});

test('fab-11: catalog NPS without LR/SR elbow — explicit error, no silent fallback', async ({ page }) => {
  await openTool(page);
  await setValues(page, { count: '3', di: '250', df: '350', angle: '35' });
  await page.locator('[data-testid="pipe-comb-fab-toggle"]').click();
  /* NPS 1/2 has no SR elbow in the B16.9 table. */
  await page.locator('#pipe-comb-fab-nps').selectOption('1/2');
  await page.locator('[data-testid="pipe-comb-fab-radius-sr"]').click();
  await page.locator('#pipe-comb-fab-lin').fill('1000');
  await page.locator('#pipe-comb-fab-lout').fill('1200');
  const error = page.locator('[data-testid="pipe-comb-fab-error"]');
  await expect(error).toBeVisible();
  await expect(error).toHaveAttribute('data-code', 'clr_not_tabulated');
  await expect(page.locator('[data-testid="pipe-comb-fab-cutlist"]')).toHaveCount(0);
});

/* ------------------------------------------------------------------ *
 * 4. Bend mode
 * ------------------------------------------------------------------ */

test('fab-12: bend mode — one bar per pipe, straight/arc breakdown, gap not applied', async ({ page }) => {
  await setupCase3x35(page);
  await page.locator('[data-testid="pipe-comb-fab-mode-bend"]').click();
  await page.locator('#pipe-comb-fab-clr').fill('228.6');
  await page.locator('#pipe-comb-fab-gap').fill('2');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
  /* Explicit module warning: the gap is not applied to a bent bar. */
  const warn = page.locator('[data-testid="pipe-comb-fab-warnings"] [data-code="weld_gap_not_applicable_bend"]');
  await expect(warn).toBeVisible();
  /* One bent bar per pipe (3), not 6 welded pups. */
  const pieces = page.locator('[data-testid="pipe-comb-fab-piece"]');
  await expect(pieces).toHaveCount(3);
  await expect(pieceRow(page, 'P1-BEND')).toHaveCount(1);
  /* Bar = straight 927.922697 + arc 139.643793 + straight 1127.922697
     = 2195.489187 mm — the weld gap is NOT deducted here. */
  await expect(pieceRow(page, 'P1-BEND').locator('td').nth(5)).toHaveText('2195.49 mm');
  /* Straight/arc breakdown is shown for the bent bar. */
  const detail = page.locator('[data-testid="pipe-comb-fab-detail"][data-piece-id="P1-BEND"]');
  await detail.locator('summary').click();
  const breakdown = await detail.textContent();
  expect(breakdown).toContain('927.92');
  expect(breakdown).toContain('139.64');
  expect(breakdown).toContain('1127.92');
  expect(breakdown).toContain('2195.49');
});

test('fab-13: mode switch preserves entries; back to catalog restores pups', async ({ page }) => {
  await setupCase3x35(page);
  await page.locator('[data-testid="pipe-comb-fab-mode-bend"]').click();
  await page.locator('#pipe-comb-fab-clr').fill('228.6');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete');
  await page.locator('[data-testid="pipe-comb-fab-mode-catalog"]').click();
  /* LR selection and references survived the mode round-trip. */
  await expect(page.locator('[data-testid="pipe-comb-fab-radius-lr"]')).toHaveAttribute('aria-pressed', 'true');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
  await expect(page.locator('[data-testid="pipe-comb-fab-piece"]')).toHaveCount(6);
  await expect(page.locator('#pipe-comb-fab-lin')).toHaveValue('1000');
});

test('fab-14: bend CLR below / equal / above OD/2', async ({ page }) => {
  await setupCase3x35(page);
  await page.locator('[data-testid="pipe-comb-fab-mode-bend"]').click();
  /* OD(6) = 168.28 -> OD/2 = 84.14. CLR = 80: intrados negative. */
  await page.locator('#pipe-comb-fab-clr').fill('80');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'invalid-plan');
  await expect(
    page.locator('[data-testid="pipe-comb-fab-warnings"] [data-code="clr_below_half_od"]'),
  ).toBeVisible();
  /* CLR exactly OD/2: zero intrados, still invalid. */
  await page.locator('#pipe-comb-fab-clr').fill('84.14');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'invalid-plan');
  /* Slightly above: valid again. */
  await page.locator('#pipe-comb-fab-clr').fill('85');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete');
});

/* ------------------------------------------------------------------ *
 * 5. Marking: material marks vs geometric references
 * ------------------------------------------------------------------ */

test('fab-15: catalog marking — intrados/extrados on material, centerline theoretical', async ({ page }) => {
  await setupCase3x35(page);
  const material = page.locator('[data-testid="pipe-comb-fab-mark"][data-material="true"]');
  const references = page.locator('[data-testid="pipe-comb-fab-mark"][data-material="false"]');
  await expect(material).toHaveCount(2);
  await expect(material.filter({ hasText: /Intrados/ })).toHaveCount(1);
  await expect(material.filter({ hasText: /Extrados/ })).toHaveCount(1);
  /* The centerline development is a THEORETICAL reference, never a
     material mark (P3-A marking-semantics fix). */
  await expect(references.filter({ hasText: /Centerline/ })).toHaveCount(2);
  await expect(material.filter({ hasText: /Centerline/ })).toHaveCount(0);
  /* Tangent-family engine values are declared as non-measurable. */
  await expect(page.locator('[data-testid="pipe-comb-fab-cutvalues"]')).toBeVisible();
  const cutValues = await page.locator('[data-testid="pipe-comb-fab-cutvalues"]').textContent();
  expect(cutValues).toContain('72.08');
  /* Model limitation note is visible. */
  await expect(page.locator('[data-testid="pipe-comb-fab-model-note"]')).toBeVisible();
});

test('fab-16: bend marking — no invented material marks', async ({ page }) => {
  await setupCase3x35(page);
  await page.locator('[data-testid="pipe-comb-fab-mode-bend"]').click();
  await page.locator('#pipe-comb-fab-clr').fill('228.6');
  await expect(page.locator('[data-testid="pipe-comb-fab-mark"][data-material="true"]')).toHaveCount(0);
  /* The module's own no-material-marks explanation is shown. */
  await expect(page.locator('[data-testid="pipe-comb-fab-marks"]')).toContainText('no marks on material');
});

/* ------------------------------------------------------------------ *
 * 6. P2 updates propagate
 * ------------------------------------------------------------------ */

test('fab-17: changing P2 angle/count recalculates the plan', async ({ page }) => {
  await setupCase3x35(page);
  /* Angle 45: t = 228.6 * tan(22.5 deg) = 94.686986 -> 94.69 mm. */
  await setValues(page, { angle: '45' });
  await expect(fabMetric(page, 'takeOut')).toHaveText('94.69 mm');
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('905.31 mm');
  /* Count 4: the fourth pipe's pups appear. */
  await setValues(page, { count: '4' });
  await expect(page.locator('[data-testid="pipe-comb-fab-piece"]')).toHaveCount(8);
  await expect(pieceRow(page, 'P4-IN')).toHaveCount(1);
});

test('fab-18: 90 degrees — no angular cut note; aligned case still computes', async ({ page }) => {
  await setupCase3x35(page);
  await setValues(page, { angle: '90' });
  await expect(page.locator('[data-testid="pipe-comb-fab-od-clr"]')).toContainText('no angular cut');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete');
  /* Aligned geometry (Di 200 / Df 100 / 60 deg -> A = 0); t(60) =
     228.6 * tan(30 deg) = 131.985231 -> P1-IN = 868.014769 mm. */
  await setValues(page, { di: '200', df: '100', angle: '60' });
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('868.02 mm');
});

/* ------------------------------------------------------------------ *
 * 7. Units and decimal policy on the new inputs
 * ------------------------------------------------------------------ */

test('fab-19: 20 unit cycles never drift Lin/Lout/CLR/gap/allowance or results', async ({ page }) => {
  await setupCase3x35(page);
  for (let i = 0; i < 20; i++) {
    await page.getByRole('button', { name: 'in', exact: true }).click();
    await page.getByRole('button', { name: 'mm', exact: true }).click();
  }
  await expect(page.locator('#pipe-comb-fab-lin')).toHaveValue('1000');
  await expect(page.locator('#pipe-comb-fab-lout')).toHaveValue('1200');
  await expect(page.locator('#pipe-comb-fab-gap')).toHaveValue('0');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
  await expect(pieceRow(page, 'P3-OUT').locator('td').nth(5)).toHaveText('1255.9 mm');
});

test('fab-20: real editing in inches and back to mm', async ({ page }) => {
  await setupCase3x35(page);
  await page.getByRole('button', { name: 'in', exact: true }).click();
  /* Display converts: 1000 mm = 39.3701 in (4-decimal inch convention). */
  await expect(page.locator('#pipe-comb-fab-lin')).toHaveValue('39.3701');
  /* Real edit: 40 in = 1016 mm. P1-IN = 943.922697 mm = 37.162315 in. */
  await page.locator('#pipe-comb-fab-lin').fill('40');
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('37.1623 in');
  await page.getByRole('button', { name: 'mm', exact: true }).click();
  await expect(page.locator('#pipe-comb-fab-lin')).toHaveValue('1016');
  /* 1016 - 72.077303 = 943.922697 mm. */
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('943.92 mm');
});

test('fab-21: comma accepted, ambiguous mixes rejected on the new inputs', async ({ page }) => {
  await setupCase3x35(page);
  await page.locator('#pipe-comb-fab-lin').fill('1000,5');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
  /* 1000.5 - 72.077303 = 928.422697 mm. */
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('928.42 mm');
  /* Ambiguous point+comma mix: localized rejection, no reinterpretation. */
  await page.locator('#pipe-comb-fab-lin').fill('10.0,5');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'review');
  await expect(page.locator('[data-testid="pipe-comb-fab-cutlist"]')).toHaveCount(0);
});

test('fab-22: negative CLR text rejected in bend mode', async ({ page }) => {
  await setupCase3x35(page);
  await page.locator('[data-testid="pipe-comb-fab-mode-bend"]').click();
  await page.locator('#pipe-comb-fab-clr').fill('-50');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'review');
  await expect(page.locator('[data-testid="pipe-comb-fab-cutlist"]')).toHaveCount(0);
});

/* ------------------------------------------------------------------ *
 * 8. Keyboard, a11y, translations
 * ------------------------------------------------------------------ */

test('fab-23: keyboard-operable toggle with accessible state', async ({ page }) => {
  await openTool(page);
  const toggle = page.locator('[data-testid="pipe-comb-fab-toggle"]');
  await toggle.focus();
  await expect(toggle).toBeFocused();
  await expect(toggle).toHaveAttribute('aria-expanded', 'false');
  await page.keyboard.press('Enter');
  await expect(toggle).toHaveAttribute('aria-expanded', 'true');
  await expect(page.locator('#pipe-comb-fab-panel')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(toggle).toHaveAttribute('aria-expanded', 'true');
  await page.keyboard.press('Tab');
  /* Status region is announced (role=status). */
  await expect(page.locator('[data-testid="pipe-comb-fab-status"]')).toHaveAttribute('role', 'status');
});

test('fab-24: Spanish localization of the section', async ({ page }) => {
  await setupCase3x35(page, TOOL_URL_ES);
  await expect(page.locator('[data-testid="pipe-comb-fab-section"] h4')).toHaveText('Fabricación y lista de corte');
  await expect(fabStatus(page)).toHaveText('Cálculo completo con advertencias.');
  await expect(page.locator('[data-testid="pipe-comb-fab-cutlist"] p').first()).toHaveText('Lista de corte');
  /* Piece notation (ids, NPS, CLR) keeps its form. */
  await expect(pieceRow(page, 'P1-IN')).toHaveCount(1);
});

test('fab-24b: Spanish localization of marking endpoints and joint detail', async ({ page }) => {
  await setupCase3x35(page, TOOL_URL_ES);
  await page.locator('#pipe-comb-fab-gap').fill('2');
  /* Mark origin/destination are localized, not raw English internals. */
  const intrados = page.locator('[data-testid="pipe-comb-fab-mark"][data-mark-id="arc-intrados-from-kept-face"]');
  await expect(intrados).toContainText('cara conservada');
  await expect(intrados).toContainText('plano de corte al ángulo conservado 35');
  const takeout = page.locator('[data-testid="pipe-comb-fab-mark"][data-mark-id="takeout-axis"]');
  await expect(takeout).toContainText('intersección teórica de ejes');
  /* Joint line localized: pup face vs elbow face, applied gap. */
  const detail = page.locator('[data-testid="pipe-comb-fab-detail"][data-piece-id="P1-IN"]');
  await detail.locator('summary').click();
  const joint = detail.locator('[data-testid="pipe-comb-fab-joint"][data-joint-id="J1-IN"]');
  await expect(joint).toHaveCount(1);
  await expect(joint).toContainText('J1-IN');
  await expect(joint).toContainText('P1-IN-FACE-J');
  await expect(joint).toContainText('P1-ELBOW-FACE-IN');
  await expect(joint).toContainText('2 mm');
});

/* ------------------------------------------------------------------ *
 * 9. Responsive + en/in presentation
 * ------------------------------------------------------------------ */

test('fab-25: mobile 320/390 — cards layout, no overflow, full cut values', async ({ page }) => {
  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 800 });
    await setupCase3x35(page);
    /* Cards visible, desktop table hidden at this width. */
    await expect(page.locator('[data-testid="pipe-comb-fab-cutlist"] table')).toBeHidden();
    const card = page.locator('[data-testid="pipe-comb-fab-piece-card"][data-piece-id="P3-OUT"]');
    await expect(card).toBeVisible();
    /* The full cut value with unit is present and unclipped. */
    await expect(card).toContainText('1255.9 mm');
    /* Real rendered geometry, not just the global overflow counter: every
       card sits inside the viewport and inside the section card. */
    const sectionBox = await page.locator('[data-testid="pipe-comb-fab-section"]').boundingBox();
    expect(sectionBox).not.toBeNull();
    for (const cardEl of await page.locator('[data-testid="pipe-comb-fab-piece-card"]').all()) {
      const box = await cardEl.boundingBox();
      expect(box).not.toBeNull();
      expect(box!.x).toBeGreaterThanOrEqual(0);
      expect(box!.x + box!.width).toBeLessThanOrEqual(width);
      expect(box!.x).toBeGreaterThanOrEqual(sectionBox!.x - 0.5);
      expect(box!.x + box!.width).toBeLessThanOrEqual(sectionBox!.x + sectionBox!.width + 0.5);
    }
    const overflow = await page.evaluate(
      () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
    );
    expect(overflow).toBeLessThanOrEqual(1);
  }
});

test('fab-26: English/inches presentation of the same case', async ({ page }) => {
  await setupCase3x35(page);
  await page.getByRole('button', { name: 'in', exact: true }).click();
  await expect(fabMetric(page, 'takeOut')).toHaveText('2.8377 in');
  await expect(fabMetric(page, 'stagger')).toHaveText('9.9673 in');
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('36.5324 in');
  await expect(pieceRow(page, 'P3-OUT').locator('td').nth(5)).toHaveText('49.445 in');
});

test('fab-27: N=12 renders a 24-piece cut list without page overflow', async ({ page }) => {
  await openTool(page);
  await setValues(page, { count: '12', di: '250', df: '350', angle: '35' });
  await page.locator('[data-testid="pipe-comb-fab-toggle"]').click();
  await page.locator('#pipe-comb-fab-nps').selectOption('6');
  await page.locator('#pipe-comb-fab-lin').fill('5000');
  await page.locator('#pipe-comb-fab-lout').fill('5000');
  await expect(page.locator('[data-testid="pipe-comb-fab-piece"]')).toHaveCount(24);
  await expect(pieceRow(page, 'P12-OUT')).toHaveCount(1);
  const overflow = await page.evaluate(
    () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
  );
  expect(overflow).toBeLessThanOrEqual(1);
});

test('fab-28: negative stagger case keeps signed presentation', async ({ page }) => {
  /* REF-03-like geometry: Di 400 / Df 200 / 45 deg -> A = -117.16 mm. */
  await openTool(page);
  await setValues(page, { count: '3', di: '400', df: '200', angle: '45' });
  await page.locator('[data-testid="pipe-comb-fab-toggle"]').click();
  await page.locator('#pipe-comb-fab-nps').selectOption('6');
  await page.locator('#pipe-comb-fab-lin').fill('2000');
  await page.locator('#pipe-comb-fab-lout').fill('2000');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
  await expect(fabMetric(page, 'stagger')).toHaveText('-117.16 mm');
  /* Stagger A is ADDITIVE for a negative stagger: axis P2-IN =
     2000 + 117.157288 - t(45) 94.686986 = 2022.470301 mm. */
  await expect(pieceRow(page, 'P2-IN').locator('td').nth(5)).toHaveText('2022.47 mm');
});

/* ------------------------------------------------------------------ *
 * 10. Integration review fixes — H1: canonical values feed the module
 * ------------------------------------------------------------------ */

test('fab-29: CLR limit case stays invalid in mm AND in inches (canonical input)', async ({ page }) => {
  await setupCase3x35(page);
  await page.locator('[data-testid="pipe-comb-fab-mode-bend"]').click();
  /* OD(6)/2 = 84.14 exactly: CLR = 84.14 is invalid (zero intrados). */
  await page.locator('#pipe-comb-fab-clr').fill('84.14');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'invalid-plan');
  /* Unit switch must NOT re-derive the consumed radius from the rounded
     display text: "3.3126" in parses to 84.14004 mm and would silently
     turn the plan valid. The canonical 84.14 mm must be consumed. */
  await page.getByRole('button', { name: 'in', exact: true }).click();
  await expect(page.locator('#pipe-comb-fab-clr')).toHaveValue('3.3126');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'invalid-plan');
  await page.getByRole('button', { name: 'mm', exact: true }).click();
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'invalid-plan');
  /* Values on both sides of the limit keep their own state in both units. */
  await page.locator('#pipe-comb-fab-clr').fill('84.13');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'invalid-plan');
  await page.locator('#pipe-comb-fab-clr').fill('84.15');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete');
  await page.getByRole('button', { name: 'in', exact: true }).click();
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete');
});

test('fab-30: Lin with sub-display precision feeds the module unrounded', async ({ page }) => {
  await setupCase3x35(page);
  /* 1000.004 mm displays as "1000" after a unit round-trip (mm 2-dec
     convention) but the module must consume the full-precision canonical
     value: P1-IN = 1000.004 - t(35) 72.077303 = 927.926697 -> 927.93 mm
     (consuming the re-parsed "1000" would give 927.92). */
  await page.locator('#pipe-comb-fab-lin').fill('1000.004');
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('927.93 mm');
  /* Inch phase consumes the SAME canonical value: 36.5325 in, not the
     display-text re-parse 36.5324. */
  await page.getByRole('button', { name: 'in', exact: true }).click();
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('36.5325 in');
  await page.getByRole('button', { name: 'mm', exact: true }).click();
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('927.93 mm');
});

test('fab-31: 20 unit cycles — every inch phase checked, no drift in any field', async ({ page }) => {
  await setupCase3x35(page);
  /* Non-representable decimals on Lin/Lout and non-zero decimal g/margin.
     P1-IN  = 1000.004 - 72.077303 - 0.03 + 0.05 = 927.946697 -> 927.95 mm / 36.5333 in.
     P1-OUT = 1200.006 - 72.077303 - 0.03 + 0.05 = 1127.948697 -> 1127.95 mm / 44.4074 in. */
  await page.locator('#pipe-comb-fab-lin').fill('1000.004');
  await page.locator('#pipe-comb-fab-lout').fill('1200.006');
  await page.locator('#pipe-comb-fab-gap').fill('0.03');
  await page.locator('#pipe-comb-fab-allowance').fill('0.05');
  for (let i = 0; i < 20; i++) {
    await page.getByRole('button', { name: 'in', exact: true }).click();
    await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('36.5333 in');
    await expect(pieceRow(page, 'P1-OUT').locator('td').nth(5)).toHaveText('44.4074 in');
    await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
    await page.getByRole('button', { name: 'mm', exact: true }).click();
    await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('927.95 mm');
    await expect(pieceRow(page, 'P1-OUT').locator('td').nth(5)).toHaveText('1127.95 mm');
  }
});

/* ------------------------------------------------------------------ *
 * 11. Integration review fixes — H2: empty/invalid never resurrect data
 * ------------------------------------------------------------------ */

test('fab-32: deleted reference stays EMPTY across a unit change', async ({ page }) => {
  await setupCase3x35(page);
  await page.locator('#pipe-comb-fab-lin').fill('');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'pending-refs');
  await page.getByRole('button', { name: 'in', exact: true }).click();
  /* Absence survives the toggle: no "39.3701" reappears from the old value. */
  await expect(page.locator('#pipe-comb-fab-lin')).toHaveValue('');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'pending-refs');
  const missingText = await page.locator('[data-testid="pipe-comb-fab-missing"]').textContent();
  expect(missingText).toContain('Lin');
  /* Lout is still valid and independently displayed. */
  await expect(page.locator('#pipe-comb-fab-lout')).toHaveValue('47.2441');
  /* A real edit in inches recovers the plan: 40 in = 1016 mm. */
  await page.locator('#pipe-comb-fab-lin').fill('40');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
  await expect(pieceRow(page, 'P1-IN').locator('td').nth(5)).toHaveText('37.1623 in');
});

test('fab-33: invalid text is never replaced by the last valid value', async ({ page }) => {
  await setupCase3x35(page);
  for (const bad of ['abc', '10.0,5']) {
    await page.locator('#pipe-comb-fab-lin').fill(bad);
    await expect(fabStatus(page)).toHaveAttribute('data-status', 'review');
    await page.getByRole('button', { name: 'in', exact: true }).click();
    await expect(page.locator('#pipe-comb-fab-lin')).toHaveValue(bad);
    await expect(fabStatus(page)).toHaveAttribute('data-status', 'review');
    await expect(page.locator('[data-testid="pipe-comb-fab-cutlist"]')).toHaveCount(0);
    await page.getByRole('button', { name: 'mm', exact: true }).click();
    await expect(page.locator('#pipe-comb-fab-lin')).toHaveValue(bad);
    await expect(fabStatus(page)).toHaveAttribute('data-status', 'review');
  }
  /* Only an explicit valid correction resolves the review state. */
  await page.locator('#pipe-comb-fab-lin').fill('1000');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'complete-warnings');
});

test('fab-34: empty/invalid states persist across close/reopen and mode switches', async ({ page }) => {
  await setupCase3x35(page);
  await page.locator('#pipe-comb-fab-lin').fill('');
  await page.locator('#pipe-comb-fab-gap').fill('abc');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'review');
  /* Close/reopen: absence and review states survive. */
  await page.locator('[data-testid="pipe-comb-fab-toggle"]').click();
  await page.locator('[data-testid="pipe-comb-fab-toggle"]').click();
  await expect(page.locator('#pipe-comb-fab-lin')).toHaveValue('');
  await expect(page.locator('#pipe-comb-fab-gap')).toHaveValue('abc');
  /* Mode round-trip: still empty/invalid, no stale values reappear. */
  await page.locator('[data-testid="pipe-comb-fab-mode-bend"]').click();
  await page.locator('#pipe-comb-fab-clr').fill('228.6');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'review');
  await page.locator('[data-testid="pipe-comb-fab-mode-catalog"]').click();
  await expect(page.locator('#pipe-comb-fab-lin')).toHaveValue('');
  await expect(page.locator('#pipe-comb-fab-gap')).toHaveValue('abc');
  /* Explicit correction of the gap recovers (Lin still pending). */
  await page.locator('#pipe-comb-fab-gap').fill('0');
  await expect(fabStatus(page)).toHaveAttribute('data-status', 'pending-refs');
});

/* ------------------------------------------------------------------ *
 * 12. Integration review fixes — H3: real responsive controls
 * ------------------------------------------------------------------ */

/** Assert a control is fully inside the viewport and the section card,
 *  and that its own text is not clipped (scrollWidth check). */
async function expectControlFullyVisible(
  page: import('@playwright/test').Page,
  selector: string,
  width: number,
  sectionBox: { x: number; width: number } | null,
) {
  const btn = page.locator(selector);
  await expect(btn).toBeVisible();
  const box = await btn.boundingBox();
  expect(box, selector).not.toBeNull();
  expect(box!.x, `${selector} inside viewport (x)`).toBeGreaterThanOrEqual(0);
  expect(box!.x + box!.width, `${selector} inside viewport (right)`).toBeLessThanOrEqual(width);
  expect(box!.x, `${selector} inside section (x)`).toBeGreaterThanOrEqual(sectionBox!.x - 0.5);
  expect(box!.x + box!.width, `${selector} inside section (right)`).toBeLessThanOrEqual(
    sectionBox!.x + sectionBox!.width + 0.5,
  );
  const clipped = await btn.evaluate((el) => el.scrollWidth - el.clientWidth);
  expect(clipped, `${selector} text not clipped`).toBeLessThanOrEqual(1);
}

const FAB_CONTROLS = [
  '[data-testid="pipe-comb-fab-toggle"]',
  '[data-testid="pipe-comb-fab-mode-catalog"]',
  '[data-testid="pipe-comb-fab-mode-bend"]',
  '[data-testid="pipe-comb-fab-radius-lr"]',
  '[data-testid="pipe-comb-fab-radius-sr"]',
  '#pipe-comb-fab-nps',
  '#pipe-comb-fab-lin',
  '#pipe-comb-fab-lout',
  '#pipe-comb-fab-gap',
  '#pipe-comb-fab-allowance',
];

test('fab-35: controls fully visible, unclipped and actionable at 320/390 (es + en)', async ({ page }) => {
  test.slow(); /* 4 full setups (2 widths x es/en) + per-control geometry checks. */
  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 800 });
    /* Spanish has the longest control labels of the locale set. */
    await setupCase3x35(page, TOOL_URL_ES);
    let sectionBox = await page.locator('[data-testid="pipe-comb-fab-section"]').boundingBox();
    expect(sectionBox).not.toBeNull();
    for (const sel of FAB_CONTROLS) await expectControlFullyVisible(page, sel, width, sectionBox);
    /* Both modes are actionable at this width; the CLR field appears. */
    await page.locator('[data-testid="pipe-comb-fab-mode-bend"]').click();
    await expect(page.locator('[data-testid="pipe-comb-fab-mode-bend"]')).toHaveAttribute('aria-pressed', 'true');
    await expectControlFullyVisible(page, '#pipe-comb-fab-clr', width, sectionBox);
    await page.locator('[data-testid="pipe-comb-fab-mode-catalog"]').click();
    await expect(page.locator('[data-testid="pipe-comb-fab-mode-catalog"]')).toHaveAttribute('aria-pressed', 'true');
    /* Status and mobile cards with full identifiers/units stay visible. */
    await expect(fabStatus(page)).toBeVisible();
    const card = page.locator('[data-testid="pipe-comb-fab-piece-card"][data-piece-id="P3-OUT"]');
    await expect(card).toBeVisible();
    await expect(card).toContainText('1255.9 mm');
    /* English: same guarantees. */
    await setupCase3x35(page);
    sectionBox = await page.locator('[data-testid="pipe-comb-fab-section"]').boundingBox();
    expect(sectionBox).not.toBeNull();
    for (const sel of FAB_CONTROLS) await expectControlFullyVisible(page, sel, width, sectionBox);
  }
});

/* ------------------------------------------------------------------ *
 * 13. Integration review fixes — H4: complete reference presentation
 * ------------------------------------------------------------------ */

test('fab-36: summary shows Lin and Lout independently; only-Lout keeps Lin pending', async ({ page }) => {
  await setupCase3x35(page);
  await expect(fabMetric(page, 'refs')).toHaveText('Lin: 1000 mm · Lout: 1200 mm');
  /* Delete Lin: Lout must still be shown, Lin explicitly pending — both
     are never hidden together just because Lin is empty. */
  await page.locator('#pipe-comb-fab-lin').fill('');
  await expect(fabMetric(page, 'refs')).toHaveText('Lin: pending · Lout: 1200 mm');
});

test('fab-37: marking shows localized origin → destination for every mark', async ({ page }) => {
  await setupCase3x35(page);
  /* Material mark: kept face -> cut plane at the kept angle. */
  const intrados = page.locator('[data-testid="pipe-comb-fab-mark"][data-mark-id="arc-intrados-from-kept-face"]');
  await expect(intrados).toContainText('kept face');
  await expect(intrados).toContainText('cut plane at kept angle 35°');
  /* Theoretical take-out: axis intersection -> elbow face plane. */
  const takeout = page.locator('[data-testid="pipe-comb-fab-mark"][data-mark-id="takeout-axis"]');
  await expect(takeout).toContainText('theoretical axis intersection');
  await expect(takeout).toContainText('elbow face plane');
  /* Method is still shown alongside the endpoints. */
  await expect(intrados).toContainText('arc development');
  /* Bend mode: tangent-to-tangent endpoints on the developed axis. */
  await page.locator('[data-testid="pipe-comb-fab-mode-bend"]').click();
  await page.locator('#pipe-comb-fab-clr').fill('228.6');
  const developed = page.locator('[data-testid="pipe-comb-fab-mark"][data-mark-id="arc-centerline-developed"]');
  await expect(developed).toContainText('tangent point T1');
  await expect(developed).toContainText('tangent point T2');
});

test('fab-38: joint detail links each pup to its elbow faces with the applied gap', async ({ page }) => {
  await setupCase3x35(page);
  await page.locator('#pipe-comb-fab-gap').fill('2');
  const detail = page.locator('[data-testid="pipe-comb-fab-detail"][data-piece-id="P1-IN"]');
  await detail.locator('summary').click();
  /* Own face and elbow face are distinct identified points when g > 0. */
  const joint = detail.locator('[data-testid="pipe-comb-fab-joint"][data-joint-id="J1-IN"]');
  await expect(joint).toHaveCount(1);
  expect(await joint.textContent()).toContain('P1-IN-FACE-J');
  expect(await joint.textContent()).toContain('P1-ELBOW-FACE-IN');
  expect(await joint.textContent()).toContain('2 mm');
  /* The outlet pup gets its own joint, not the inlet's. */
  const outDetail = page.locator('[data-testid="pipe-comb-fab-detail"][data-piece-id="P1-OUT"]');
  await outDetail.locator('summary').click();
  const outJoint = outDetail.locator('[data-testid="pipe-comb-fab-joint"][data-joint-id="J1-OUT"]');
  await expect(outJoint).toHaveCount(1);
  expect(await outJoint.textContent()).toContain('P1-OUT-FACE-J');
  /* The elbow piece itself does not own the pup-side joint line. */
  const elbowDetail = page.locator('[data-testid="pipe-comb-fab-detail"][data-piece-id="P1-ELBOW"]');
  await elbowDetail.locator('summary').click();
  await expect(elbowDetail.locator('[data-testid="pipe-comb-fab-joint"]')).toHaveCount(0);
  /* g = 0 is shown explicitly (0 mm), not hidden. */
  await page.locator('#pipe-comb-fab-gap').fill('0');
  await expect(joint).toContainText('0 mm');
});
