#!/usr/bin/env python3
"""H-001 print delta: add picaje-template + PDF keys to all 11 locales."""
import json
from collections import OrderedDict
import io

LOCALES = {
 'en': {'printPicaje1to1':'Print picaje template 1:1','picajeTemplateTitle':'Header picaje template 1:1 — opening','picajeOrigin':'Origin (0,0)','picajeOpeningNote':'Line = nominal opening (reference: branch ID). No bevel or cutting allowance in V1.','picajeWrapNote':'X = developed circumferential distance on the header surface (wrap direction). Y = axial distance along the header. Align X = 0 with the reference generatrix.','picajeDims':'Opening: {w} mm (X) × {h} mm (Y)','pdfDownloaded':'PDF downloaded — print at 100% / Actual Size, no fit-to-page'},
 'es': {'printPicaje1to1':'Imprimir plantilla de picaje 1:1','picajeTemplateTitle':'Plantilla de picaje del colector 1:1 — abertura','picajeOrigin':'Origen (0,0)','picajeOpeningNote':'Línea = abertura nominal (referencia: ID del ramal). Sin chaflán ni allowance de corte en V1.','picajeWrapNote':'X = distancia circunferencial desarrollada sobre la superficie del colector (dirección de envolvado). Y = distancia axial a lo largo del colector. Alinear X = 0 con la generatriz de referencia.','picajeDims':'Abertura: {w} mm (X) × {h} mm (Y)','pdfDownloaded':'PDF descargado — imprimir al 100% / tamaño real, sin ajustar a página'},
 'pt': {'printPicaje1to1':'Imprimir gabarito de picagem 1:1','picajeTemplateTitle':'Gabarito de picagem do coletor 1:1 — abertura','picajeOrigin':'Origem (0,0)','picajeOpeningNote':'Linha = abertura nominal (referência: ID do ramal). Sem chanfro nem folga de corte na V1.','picajeWrapNote':'X = distância circunferencial desenvolvida na superfície do coletor (direção de envolvimento). Y = distância axial ao longo do coletor. Alinhar X = 0 com a geratriz de referência.','picajeDims':'Abertura: {w} mm (X) × {h} mm (Y)','pdfDownloaded':'PDF baixado — imprima a 100% / tamanho real, sem ajustar à página'},
 'fr': {'printPicaje1to1':'Imprimer le gabarit de traçage 1:1','picajeTemplateTitle':'Gabarit de traçage du collecteur 1:1 — ouverture','picajeOrigin':'Origine (0,0)','picajeOpeningNote':'Ligne = ouverture nominale (référence : ID du piquage). Pas de chanfrein ni de surépaisseur de coupe en V1.','picajeWrapNote':'X = distance circonférentielle développée sur la surface du collecteur (sens d’enroulement). Y = distance axiale le long du collecteur. Aligner X = 0 sur la génératrice de référence.','picajeDims':'Ouverture : {w} mm (X) × {h} mm (Y)','pdfDownloaded':'PDF téléchargé — imprimez à 100 % / taille réelle, sans ajustement à la page'},
 'de': {'printPicaje1to1':'Picaje-Schablone 1:1 drucken','picajeTemplateTitle':'Picaje-Schablone des Sammlers 1:1 — Öffnung','picajeOrigin':'Nullpunkt (0,0)','picajeOpeningNote':'Linie = Nennöffnung (Referenz: Abzweig-ID). Keine Fase und keinen Schnittpauschbetrag in V1.','picajeWrapNote':'X = abgewickelter Umfangsabstand auf der Sammleroberfläche (Wickelrichtung). Y = Axialabstand entlang des Sammlers. X = 0 auf die Bezugsmantellinie ausrichten.','picajeDims':'Öffnung: {w} mm (X) × {h} mm (Y)','pdfDownloaded':'PDF heruntergeladen — mit 100 % / Originalgröße drucken, nicht an Seite anpassen'},
 'it': {'printPicaje1to1':'Stampa template di piccaggio 1:1','picajeTemplateTitle':'Template di piccaggio del collettore 1:1 — apertura','picajeOrigin':'Origine (0,0)','picajeOpeningNote':'Linea = apertura nominale (riferimento: ID del ramo). Nessuna smussatura né sovrametallo di taglio in V1.','picajeWrapNote':'X = distanza circonferenziale sviluppata sulla superficie del collettore (direzione di avvolgimento). Y = distanza assiale lungo il collettore. Allineare X = 0 con la generatrice di riferimento.','picajeDims':'Apertura: {w} mm (X) × {h} mm (Y)','pdfDownloaded':'PDF scaricato — stampare al 100% / dimensione reale, senza adattare alla pagina'},
 'nl': {'printPicaje1to1':'Picaje-sjabloon 1:1 afdrukken','picajeTemplateTitle':'Picaje-sjabloon van de collector 1:1 — opening','picajeOrigin':'Oorsprong (0,0)','picajeOpeningNote':'Lijn = nominale opening (referentie: ID van de tak). Geen afschuining of snijtoeslag in V1.','picajeWrapNote':'X = ontwikkelde omtrekafstand op het collectoroppervlak (wikkelrichting). Y = axiale afstand langs de collector. X = 0 op de referentie-lijn uitlijnen.','picajeDims':'Opening: {w} mm (X) × {h} mm (Y)','pdfDownloaded':'PDF gedownload — print op 100% / werkelijke grootte, niet aanpassen aan pagina'},
 'pl': {'printPicaje1to1':'Drukuj szablon picaje 1:1','picajeTemplateTitle':'Szablon picaje kolektora 1:1 — otwór','picajeOrigin':'Początek (0,0)','picajeOpeningNote':'Linia = otwór nominalny (odniesienie: ID odgałęzienia). Bez fazy i naddatku na cięcie w V1.','picajeWrapNote':'X = rozwinięta odległość obwodowa na powierzchni kolektora (kierunek owijania). Y = odległość osiowa wzdłuż kolektora. Wyrównaj X = 0 z tworzącą odniesienia.','picajeDims':'Otwór: {w} mm (X) × {h} mm (Y)','pdfDownloaded':'Plik PDF pobrany — drukuj w 100% / rzeczywisty rozmiar, bez dopasowania do strony'},
 'ro': {'printPicaje1to1':'Tipărește șablonul de picaj 1:1','picajeTemplateTitle':'Șablon de picaj al colectorului 1:1 — deschidere','picajeOrigin':'Origine (0,0)','picajeOpeningNote':'Linia = deschidere nominală (referință: ID-ul ramurii). Fără tesire și fără adaos de tăiere în V1.','picajeWrapNote':'X = distanța circumferentială dezvoltată pe suprafața colectorului (direcția de înfășurare). Y = distanța axială de-a lungul colectorului. Aliniați X = 0 cu generatoarea de referință.','picajeDims':'Deschidere: {w} mm (X) × {h} mm (Y)','pdfDownloaded':'PDF descărcat — tipăriți la 100% / dimensiune reală, fără ajustare la pagină'},
 'bg': {'printPicaje1to1':'Принтиране на шаблон за picaje 1:1','picajeTemplateTitle':'Шаблон за picaje на колектора 1:1 — отвор','picajeOrigin':'Начало (0,0)','picajeOpeningNote':'Линия = номинален отвор (референция: ID на клона). Без скос и без допуск за рязане във V1.','picajeWrapNote':'X = развъгната окръжна разстояние по повърхността на колектора (посока на обвиване). Y = аксиално разстояние по колектора. Изравнете X = 0 с референтната образуваща.','picajeDims':'Отвор: {w} mm (X) × {h} mm (Y)','pdfDownloaded':'PDF изтеглен — печатайте на 100% / действителен размер, без побиране в страницата'},
 'uk': {'printPicaje1to1':'Друкувати шаблон picaje 1:1','picajeTemplateTitle':'Шаблон picaje колектора 1:1 — отвір','picajeOrigin':'Початок (0,0)','picajeOpeningNote':'Лінія = номінальний отвір (референс: ID відгалуження). Без фаски та без припуску на різання у V1.','picajeWrapNote':'X = розгорнута колова відстань по поверхні колектора (напрям обгортання). Y = аксіальна відстань уздовж колектора. Вирівняйте X = 0 з референтною твірною.','picajeDims':'Отвір: {w} мм (X) × {h} мм (Y)','pdfDownloaded':'PDF завантажено — друкуйте у 100% / реальний розмір, без вписування в сторінку'},
}

BASE='src/i18n/locales/{}.json'
for loc,vals in LOCALES.items():
    path=BASE.format(loc)
    with io.open(path,encoding='utf-8') as f:
        data=json.load(f,object_pairs_hook=OrderedDict)
    bl=data['tools']['branchLayout']
    for k,v in vals.items():
        bl[k]=v
    with io.open(path,'w',encoding='utf-8') as f:
        json.dump(data,f,ensure_ascii=False,indent=2)
        f.write('\n')
    print(f'{loc}: +{len(vals)} keys')
print('done')
